### PR TITLE
pt-PT human localization

### PR DESCRIPTION
**Pull request by nebeker**

### CODE REVIEW

**Comment by rxhanson** [comment]
Thanks for another localization! I'm running out of apps to give you licenses for, haha.

**Comment by nebeker** [comment]
No problem.

That sounds like a great excuse to keep making interesting apps!

**Comment by rxhanson** [comment]
Too many ideas, too little time ;)

I updated your coupon code in gitter.im

**Comment by nebeker** [comment]
Thanks, I'll check it out.

**Pull request merged**
