### PR TITLE
Update Main.strings

### PR DESCRIPTION
**Pull request by YogiRambo**
Made changes to Dutch language; added and changed some sentences

### CODE REVIEW

**Comment by rxhanson** [comment]
Thanks! Email me or message me on https://gitter.im for a Middle license!

**Comment by YogiRambo** [comment]
Hi Ryan,

Thanks for merging my suggestions! I would be very happy to receive a
license, since I am a great fan!
Thanks!!!! :)

Kind regards,

Yoginder

**Comment by rxhanson** [comment]
Great! I'll just need your email address or some way to send a key your way :)

**Comment by YogiRambo** [comment]
Hi Ryan,

My mailadress: yogindermail@gmail.com

Thanks!

**Pull request merged**
